# CATEGORIES ----------------------------------------------
GET http://localhost:4021/categories
content-type: application/json

###
POST http://localhost:4021/category/create 
content-type: application/json

{
  "name": "sample-5",
  "description": "sample-5-description"
}

###
POST http://localhost:4021/category/645b13027d54a34765681ccd/update
content-type: application/json

{
  "name": "sample-4-update-delete",
  "description": "sample-description-4-update-delete"
}

###
POST http://localhost:4021/category/6458e5457ce23d6b10343914/delete
content-type: application/json

###
# PRODUCTS ----------------------------------------------
GET http://localhost:4021/products

###
POST http://localhost:4021/product/create
content-type: application/json

{
    "name":"sample-product-1",
    "description":"sample-description",
    "price":1111.1,
    "category":"6458ac4830a36937e74a423a",
    "img_name":"sample-image"
}

###
POST http://localhost:4021/product/6458e5accafaf52e58559a60/update
content-type: application/json

{
    "name":"sample-product-upate",
    "description":"sample-description-update",
    "price":2222.1,
    "category":"6458ac4830a36937e74a423a",
    "img_name":"sample-image",
}

###
POST http://localhost:4021/plant-product/create
content-type: application/json

{
    "name":"sample-plant-product-create-2",
    "description":"sample-description-plant-create-2",
    "price":2222.1,
    "category":"6458ac4830a36937e74a423a",
    "img_name":"sample-image",
    "height":10,
    "pot_diameter":10,
    "type":"indoor"
}

###
POST http://localhost:4021/plant-product/6458f74842f1c51ddd0a89ce/update
content-type: application/json

{
    "name":"sample-plant-product-update-2",
    "description":"sample-description-update-2",
    "price":2222.1,
    "category":"6458ac4830a36937e74a423a",
    "img_name":"sample-image-update",
    "height":111,
    "pot_diameter":222,
    "type":"outdoor"
}

###
POST http://localhost:4021/view-product
content-type: application/json

{
    "user":"sample-user",
    "product":"sample-product"
}
###
# USERS ----------------------------------------------
GET http://localhost:4021/users

###
GET http://localhost:4021/user/645a4fbd6f19b6cd2903c16c

###
POST http://localhost:4021/user/create
content-type: application/json

{
	"name": "sample-admin",
	"email":  "admin@sample.com",
	"password": "1234",
	"type": "admin"
}

###
POST http://localhost:4021/user/645a4fbd6f19b6cd2903c16c/update
content-type: application/json

{
	"name": "sample-admin-update",
	"email":  "admin-update@sample.com",
	"password": "1234",
	"type": "admin"
}

###
POST http://localhost:4021/customer/create
content-type: application/json

{
	"name": "sample-customer-2",
	"username": "sample-username-2",
	"email":  "customer2@sample.com",
	"password": "1234",
	"type": "customer"
}

###
POST http://localhost:4021/customer/645a59e36f19b6cd2903c179/update
content-type: application/json

{
	"name": "sample-customer-update-2",
	"username": "sample-username-update-2",
	"email":  "customer-update2@sample.com",
	"password": "1234",
	"type": "customer"
}

###
POST http://localhost:4021/login-customer


###
# CART ITEMS ----------------------------------------------
GET http://localhost:4021/cart-items

###
GET http://localhost:4021/customer/645a536f6f19b6cd2903c174/cart-items

###
GET http://localhost:4021/cart-item/645b0dd37f01005f89a8a92c

###
POST http://localhost:4021/cart-item/create
content-type: application/json

{
	"customer": "645a536f6f19b6cd2903c174", 
	"product": "6458e591c82443471361b6b3"
}

###
POST http://localhost:4021/cart-item/645b0dd37f01005f89a8a92c/update
content-type: application/json

{
	"customer": "645a536f6f19b6cd2903c174", 
	"product": "6458f74842f1c51ddd0a89ce",
	"quantity": 23
}


###
POST http://localhost:4021/cart-item/645b0d6e7f01005f89a8a925/delete
content-type: application/json